name: grep-test
on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: '.net version'
        required: true
        default: '8.0'
        options:
          - '8.0'
          - '9.0'
        
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: チェックアウトリポジトリ
      uses: actions/checkout@v2

    - name: スキャン結果の保存
      run: grep -r "blazor" . --exclude-dir={.git,.github} --exclude=api_usage.txt > api_usage${{ github.event.inputs.version }}.txt

    - name: アーティファクトのアップロード
      uses: actions/upload-artifact@v4
      with:
        name: api-usage
        path: api_usage.txt
