name: grep-test
on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: '.net version'
        default: '8.0'
        options:
          - '8.0'
          - '9.0'
        
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: チェックアウトリポジトリ
      uses: actions/checkout@v2

    - name: .NETFrameworkから.NETCoreへの破壊的変更
      run: |
         patterns=$(cat .github/workflows/pattern-framwork-to-core.txt)
         for pattern in $patterns; do
           grep -r $pattern . --exclude-dir={.git,.github} -H -n -C 2 | sed "s/^/$pattern: /" >> .github/grep-results-framwork-to-core.txt || true
         done

    - name: .NETCoreと.NET5以降でサポートされていないAPI
      run: |
         patterns=$(cat .github/workflows/pattern-unsupported-core-and-after-5.txt)
         for pattern in $patterns; do
           grep -r $pattern . --exclude-dir={.git,.github} -H -n -C 2 | sed "s/^/$pattern: /" >> .github/grep-results-unsupported-core-and-after-5.txt || true
         done

    - name: .NETにおける破壊的変更
      run: |
         patterns=$(cat .github/workflows/pattern-net-disruptive-changes-${{ github.event.inputs.version }}.txt)
         for pattern in $patterns; do
           grep -r $pattern . --exclude-dir={.git,.github} -H -n -C 2 | sed "s/^/$pattern: /" >> .github/grep-results-net-disruptive-changes.txt || true
         done

    - name: アーティファクトのアップロード
      uses: actions/upload-artifact@v4
      with:
        name: api-usage
        path: |
          .github/grep-results-framwork-to-core.txt
          .github/grep-results-unsupported-core-and-after-5.txt
          .github/grep-results-net-disruptive-changes.txt
