name: grep-test
on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: '.net version'
        default: '8.0'
        options:
          - '8.0'
          - '9.0'
        
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: チェックアウトリポジトリ
      uses: actions/checkout@v2

    - name: .NETFrameworkから.NETCoreへの破壊的変更
      run: grep -r -f .github/workflows/pattern-framwork-to-core.txt . --exclude-dir={.git,.github} --exclude=grep-results-*.txt > grep-results-framwork-to-core.txt

    - name: .NETCoreと.NET5以降でサポートされていないAPI
      run: grep -r -f .github/workflows/pattern-unsupported-core-and-after-5.txt . --exclude-dir={.git,.github} --exclude=grep-results-*.txt > grep-results-unsupported-core-and-after-5.txt

    - name: .NETにおける破壊的変更1
      run: grep -r -f .github/workflows/pattern-net-disruptive-changes-8.0.txt . --exclude-dir={.git,.github} --exclude=grep-results-*.txt > grep-results-net-disruptive-changes.txt

    - name: .NETにおける破壊的変更
      run: grep -r -f .github/workflows/pattern-net-disruptive-changes-${{ github.event.inputs.version }}.txt . --exclude-dir={.git,.github} --exclude=grep-results-*.txt > grep-results-net-disruptive-changes.txt

    - name: アーティファクトのアップロード
      uses: actions/upload-artifact@v4
      with:
        name: api-usage
        path: |
          grep-results-framwork-to-core.txt
          grep-results-unsupported-core-and-after-5.txt
          grep-results-net-disruptive-changes.txt
