name: grep-test
on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: '.net version'
        default: '8.0'
        options:
          - '8.0'
          - '9.0'
        
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: チェックアウトリポジトリ
      uses: actions/checkout@v2

    - name: output ディレクトリ作成
      run: mkdir output

    - name: .NETFrameworkから.NETCoreへの破壊的変更
      run: |
         patterns=$(cat .github/patterns-deprecated-api/breaking-changes-fw-to-core.txt)
         for pattern in $patterns; do
           grep -r $pattern . --exclude-dir={.git,.github,output} -H -n -C 2 | sed "s/^/$pattern: /" >> output/grep-results-breaking-changes-fw-to-core.txt || true
         done

    - name: .NETCoreと.NET5以降でサポートされていないAPI
      run: |
         patterns=$(cat .github/patterns-deprecated-api/unsupported-api.txt)
         for pattern in $patterns; do
           grep -r $pattern . --exclude-dir={.git,.github,output} -H -n -C 2 | sed "s/^/$pattern: /" >> output/unsupported-api.txt || true
         done

    - name: .NETにおける破壊的変更
      run: |
         patterns=$(cat .github/patterns-deprecated-api/breaking-changes-net-${{ github.event.inputs.version }}.txt)
         for pattern in $patterns; do
           grep -r $pattern . --exclude-dir={.git,.github,output} -H -n -C 2 | sed "s/^/$pattern: /" >> output/grep-results-breaking-changes-net-${{ github.event.inputs.version }}.txt || true
         done

    - name: アーティファクトのアップロード
      uses: actions/upload-artifact@v4
      with:
        name: api-usage
        path: |
          output/grep-results-breaking-changes-fw-to-core.txt
          output/unsupported-api.txt
          output/grep-results-breaking-changes-net-${{ github.event.inputs.version }}.txt
